# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c27fa8d9b21f49a37cf3ae6a991eab43695c8a2eb6555b2324852a0cda13d8ae7028188b659abb403e515cd5737d7ca2e050e04cc624482cd35b93123e86772a

test:
  secret_key_base: 589a1ebb45846452dc58170547cdb015dfdb234c8605105ad4efe6a5c5777d30c524dc26ca5bd3c1961fc0c770aa8b35504cdca6b4ce14ce87cbf922eb20deec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
